import type { IdeationResult } from '../ideation/types.js';

export type QuestionCategory = 'prize_selection' | 'sponsor_selection' | 'optimization' | 'project_idea';

export type OptimizationBudget = 'minimal' | 'balanced' | 'aggressive';

export interface InterviewInfluence {
  prize?: string;
  sponsorApis?: string[];
  optimizationBudget?: OptimizationBudget;
  projectIdea?: string;
  technologyPreference?: string[];
}

export interface InterviewOption {
  value: string;
  label: string;
  description: string;
  influences: InterviewInfluence;
}

export interface InterviewQuestion {
  id: string;
  text: string;
  category: QuestionCategory;
  options: InterviewOption[];
  required: boolean;
  dependsOn: string[];
  skipLabel?: string;
}

export interface InterviewState {
  currentQuestionIndex: number;
  answers: Record<string, string | null>;
  skipped: string[];
  completed: boolean;
}

export interface InterviewResult {
  selectedPrize: string | null;
  selectedSponsorApis: string[];
  optimizationBudget: OptimizationBudget;
  userProjectIdea: string | null;
  autoGeneratedIdea: string | null;
  technologyPreferences: string[];
  allAnswers: Record<string, string | null>;
  /**
   * Full startup-quality brainstorm (20 ideas → rank → top 5 → winner) when
   * the idea was auto-generated. `autoGeneratedIdea` carries the winner's
   * one-liner for backward compatibility.
   */
  ideation?: IdeationResult | null;
}
