import type { CompetitionAnalysis, FeaturePriority, RoadmapPhase, TechnologyStack, UIDirection, WinningStrategy } from './types.js';
import type { InterviewResult } from '../interview/types.js';

/**
 * Generates a winning strategy based on parsed competition data.
 * Recommendations are context-aware: time pressure, sponsor requirements, and judging criteria
 * determine the architecture, not a hardcoded default.
 *
 * NOTE: estimatedJudgeScore is a heuristic derived from judging criteria weights.
 * It represents an upper-bound estimate, not a measured or predicted score.
 */
export class WinningStrategyGenerator {
  generate(analysis: CompetitionAnalysis, interviewResult?: InterviewResult): WinningStrategy {
    const criteria = analysis.judgingCriteria;
    const topCriteria = [...criteria].sort((a, b) => b.weight - a.weight).slice(0, 3);
    const mustAPIs = analysis.sponsorAPIs.filter(a => a.strategicValue === 'must_use');
    const shouldAPIs = analysis.sponsorAPIs.filter(a => a.strategicValue === 'should_use');
    let allAPIs = [...mustAPIs, ...shouldAPIs];

    // When interview selected specific APIs, filter to only those
    if (interviewResult && interviewResult.selectedSponsorApis.length > 0) {
      const selected = interviewResult.selectedSponsorApis;
      allAPIs = allAPIs.filter(a => selected.includes(a.name));
      if (allAPIs.length === 0) {
        allAPIs = [...mustAPIs, ...shouldAPIs];
      }
    }

    // Choose architecture based on parsed data, not hardcoded defaults
    const architecture = this.selectArchitecture(analysis);
    const stack = this.selectStack(analysis);
    const techStack = this.selectTechnologyStack(analysis, architecture, stack);
    const uiDirection = this.selectUIDirection(analysis, stack);
    const featurePriority = this.generateFeaturePriority(analysis);
    const roadmap = this.generateRoadmap(analysis, featurePriority, interviewResult);

    return {
      projectName: analysis.challenge.title.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase(),
      oneLiner: interviewResult?.userProjectIdea ?? interviewResult?.autoGeneratedIdea ?? `${analysis.challenge.title} — ${analysis.challenge.theme} solution targeting ${topCriteria.map(c => c.name).join(', ')}`,
      whyScoreWell: [
        `Directly addresses top criteria: ${topCriteria.map(c => `${c.name} (${c.weight}%)`).join(', ')}`,
        'Live, deployed demo that judges can access immediately without setup',
        allAPIs.length > 0
          ? `Integrates ${allAPIs.map(a => a.name).join(', ')} for sponsor eligibility`
          : 'Clean, focused implementation that demonstrates core functionality',
      ],
      targetedCriteria: topCriteria.map(c => ({
        name: c.name,
        weight: c.weight,
        approach: `Lead the demo with ${c.name}. Dedicate the first 30 seconds to showing how the project addresses this criterion.`,
      })),
      prioritizedAPIs: [...mustAPIs.map(a => a.name), ...shouldAPIs.map(a => a.name)],
      architecture,
      differentiators: [
        'Live demo URL — judges do not need to install or configure anything',
        'Direct alignment with top-weighted judging criteria',
        allAPIs.length > 0 ? `Sponsor API integration: ${allAPIs.map(a => a.name).join(', ')}` : 'Clean, focused implementation',
      ],
      risks: [
        { risk: 'Building more features than time allows', mitigation: 'Implement one feature end-to-end before starting the next' },
        { risk: 'Deployment fails at the last minute', mitigation: 'Deploy a skeleton in the first 15 minutes, then iterate' },
        ...(mustAPIs.length > 0
          ? [{ risk: `${mustAPIs[0]!.name} API integration fails`, mitigation: 'Integrate and verify in the first 30 minutes; prepare a fallback demo' }]
          : []),
      ],
      recommendedStack: stack,
      estimatedJudgeScore: Math.min(90, Math.round(criteria.reduce((s, c) => s + c.weight * 0.75, 0))),
      technologyStack: techStack,
      uiDirection,
      featurePriority,
      roadmap,
    };
  }

  private selectArchitecture(analysis: CompetitionAnalysis): string {
    const mustAPIs = analysis.sponsorAPIs.filter(a => a.strategicValue === 'must_use');
    const apiNames = mustAPIs.map(a => a.name.toLowerCase()).join(' ');

    // Sponsor-driven architecture choices
    if (apiNames.includes('firebase')) return 'Static frontend + Firebase: direct SDK integration, no backend server needed';
    if (apiNames.includes('twilio')) return 'Node.js + Express: SMS/voice API integration, lightweight backend';
    if (apiNames.includes('stripe')) return 'Next.js + Stripe: built-in payment flow, serverless deployment';
    if (apiNames.includes('openai') || apiNames.includes('gemini')) return 'Python/FastAPI or Next.js + AI SDK: quick AI prototype, single deploy target';
    if (apiNames.includes('supabase')) return 'SvelteKit or Next.js + Supabase: real-time capable, managed backend';

    // Theme-driven architecture
    const theme = analysis.challenge.theme.toLowerCase();
    if (theme.includes('ai') || theme.includes('ml') || theme.includes('llm')) {
      return 'Python + FastAPI or Next.js + Vercel AI SDK: rapid AI prototyping, minimal setup';
    }
    if (theme.includes('mobile')) return 'React Native or PWA: single codebase for web + mobile';
    if (theme.includes('data') || theme.includes('dashboard')) return 'Next.js + Chart.js + SQLite: single-repo data viz, no external DB needed';

    // Default: simple full-stack
    return 'Next.js + SQLite (via better-sqlite3): single-repo full-stack, zero-config deploy to Vercel';
  }

  private selectStack(analysis: CompetitionAnalysis): string[] {
    const mustAPIs = analysis.sponsorAPIs.filter(a => a.strategicValue === 'must_use');
    const theme = analysis.challenge.theme.toLowerCase();

    const stack: string[] = [];

    // Choose framework based on sponsor APIs and theme
    if (mustAPIs.some(a => a.name.toLowerCase().includes('firebase'))) {
      stack.push('Vanilla JS', 'Firebase', 'Firebase Hosting');
    } else if (mustAPIs.some(a => /openai|gemini|hugging/i.test(a.name))) {
      stack.push('Next.js', 'Vercel AI SDK', 'Vercel');
    } else if (theme.includes('mobile') || theme.includes('pwa')) {
      stack.push('React', 'Vite', 'Netlify');
    } else if (theme.includes('data') || theme.includes('dashboard') || theme.includes('analytics')) {
      stack.push('Next.js', 'Chart.js', 'SQLite', 'Vercel');
    } else {
      stack.push('Next.js', 'TypeScript', 'Tailwind CSS', 'Vercel');
    }

    return stack;
  }

  private selectTechnologyStack(analysis: CompetitionAnalysis, architecture: string, stack: string[]): TechnologyStack {
    const flat = stack.join(' ').toLowerCase();
    const theme = analysis.challenge.theme.toLowerCase();
    const archLow = architecture.toLowerCase();

    const frontend = flat.includes('next.js') ? 'Next.js' :
      flat.includes('react') && !flat.includes('next') ? 'React + Vite' :
      flat.includes('svelte') ? 'SvelteKit' :
      theme.includes('mobile') ? 'React Native' : 'Next.js';

    const backend = flat.includes('fastapi') ? 'Python FastAPI' :
      flat.includes('express') ? 'Express.js' :
      flat.includes('firebase') || archLow.includes('firebase') ? 'Firebase Functions' :
      flat.includes('next.js') || archLow.includes('next.js') ? 'Next.js API Routes' :
      'Next.js API Routes';

    const database = flat.includes('firebase') ? 'Firebase Firestore' :
      flat.includes('supabase') ? 'Supabase' :
      flat.includes('sqlite') ? 'SQLite (better-sqlite3)' :
      flat.includes('chart.js') ? 'SQLite (better-sqlite3)' : 'SQLite (better-sqlite3)';

    const deployment = flat.includes('vercel') ? 'Vercel' :
      flat.includes('netlify') ? 'Netlify' :
      flat.includes('firebase hosting') || archLow.includes('firebase') ? 'Firebase Hosting' : 'Vercel';

    const testing = flat.includes('vitest') ? 'Vitest' : 'Vitest';

    const styling = flat.includes('tailwind') ? 'Tailwind CSS' : 'Tailwind CSS';

    return { frontend, backend, database, deployment, testing, styling };
  }

  private selectUIDirection(analysis: CompetitionAnalysis, stack: string[]): UIDirection {
    const theme = analysis.challenge.theme.toLowerCase();
    const flat = stack.join(' ').toLowerCase();

    const designLanguage = theme.includes('ai') || theme.includes('ml') ? 'Minimal, data-focused with emphasis on model outputs' :
      theme.includes('mobile') ? 'Mobile-first with touch-optimized interactions' :
      theme.includes('data') || theme.includes('dashboard') ? 'Dashboard-centric with data visualizations' :
      theme.includes('game') ? 'Playful with vibrant colors and animations' :
      theme.includes('health') || theme.includes('wellness') ? 'Calming palette, accessible typography, rounded corners' :
      theme.includes('edu') ? 'Clean, readable with clear information hierarchy' :
      'Modern, clean with generous whitespace and subtle shadows';

    const layout = theme.includes('ai') || theme.includes('data') ? 'Full-width content area with sidebar navigation' :
      theme.includes('mobile') ? 'Single-column scroll with bottom tab navigation' :
      'Centered card-based layout with top navigation bar';

    const keyScreens: string[] = [];
    keyScreens.push('Landing / Hero');
    keyScreens.push('Core Feature / Dashboard');
    keyScreens.push('Submission / Result');

    const responsiveBreakpoints = 'Mobile (375px), Tablet (768px), Desktop (1280px)';

    const componentLibrary = flat.includes('tailwind') ? 'Tailwind CSS + custom components' :
      'Custom CSS components';

    return { designLanguage, layout, keyScreens, responsiveBreakpoints, componentLibrary };
  }

  private generateFeaturePriority(analysis: CompetitionAnalysis): FeaturePriority[] {
    const features: FeaturePriority[] = [];
    const theme = analysis.challenge.theme.toLowerCase();
    const topCriteria = [...analysis.judgingCriteria].sort((a, b) => b.weight - a.weight);

    topCriteria.forEach((c, i) => {
      features.push({
        feature: `${c.name} showcase — demo that explicitly highlights ${c.name}`,
        weight: c.weight,
        effort: i === 0 ? 'high' : i === 1 ? 'medium' : 'low',
        category: 'core',
      });
    });

    const mustAPIs = analysis.sponsorAPIs.filter(a => a.strategicValue === 'must_use');
    const shouldAPIs = analysis.sponsorAPIs.filter(a => a.strategicValue === 'should_use');

    mustAPIs.forEach(a => {
      features.push({
        feature: `${a.name} API integration with live demo`,
        weight: 25,
        effort: 'medium',
        category: 'sponsor',
      });
    });

    shouldAPIs.forEach(a => {
      features.push({
        feature: `${a.name} integration demonstration`,
        weight: 15,
        effort: 'medium',
        category: 'sponsor',
      });
    });

    features.push({
      feature: 'Responsive UI with polished interactions',
      weight: 10,
      effort: 'medium',
      category: 'polish',
    });
    features.push({
      feature: 'Deployed live demo accessible via URL',
      weight: 15,
      effort: 'low',
      category: 'core',
    });

    return features;
  }

  private generateRoadmap(analysis: CompetitionAnalysis, features: FeaturePriority[], interviewResult?: InterviewResult): RoadmapPhase[] {
    const budget = interviewResult?.optimizationBudget ?? 'balanced';
    const timePerPhase = budget === 'minimal' ? 60 : budget === 'aggressive' ? 120 : 90;

    return [
      {
        phase: 'Project scaffold & deployment skeleton',
        tasks: [
          'Initialize project with chosen framework',
          'Set up deployment pipeline (Vercel/Netlify)',
          'Create basic app shell with routing',
          'Configure styling framework',
        ],
        estimatedMinutes: 15,
      },
      {
        phase: 'Core feature implementation',
        tasks: features
          .filter(f => f.category === 'core')
          .slice(0, 3)
          .map(f => `Implement ${f.feature.toLowerCase()}`),
        estimatedMinutes: timePerPhase,
      },
      {
        phase: 'Sponsor API integration',
        tasks: features
          .filter(f => f.category === 'sponsor')
          .map(f => `Integrate and demo ${f.feature.toLowerCase()}`),
        estimatedMinutes: timePerPhase,
      },
      {
        phase: 'Polish & submission prep',
        tasks: [
          'Refine UI/UX with responsive design pass',
          'Add loading states and error handling',
          'Write README with setup instructions',
          'Record demo video or prepare live walkthrough',
          'Submit on Devpost with all required fields',
        ],
        estimatedMinutes: budget === 'minimal' ? 30 : 45,
      },
    ];
  }
}
