import { describe, it, expect } from 'vitest';

import { brainstormIdeas } from '../../cli/ideation/idea-engine.js';
import { IDEATION_POOL_SIZE, IDEATION_SHORTLIST_SIZE } from '../../cli/ideation/idea-engine.js';
import type { InterviewResult } from '../../cli/interview/types.js';
import type { CompetitionAnalysis } from '../../cli/pipeline/types.js';

function mockAnalysis(overrides?: Partial<CompetitionAnalysis>): CompetitionAnalysis {
  return {
    analysisId: 'ca-test',
    challenge: {
      title: 'AI for Good Hackathon',
      problemStatement: 'Build AI solutions for social impact',
      theme: 'AI for Good',
      difficulty: 'intermediate',
      estimatedParticipants: 200,
      organizer: 'TestOrg',
    },
    judgingCriteria: [
      { name: 'Innovation', weight: 40, weightRaw: '40%', description: 'Originality', priority: 'critical' },
      { name: 'Technical Depth', weight: 30, weightRaw: '30%', description: 'Sophistication', priority: 'high' },
      { name: 'Social Impact', weight: 30, weightRaw: '30%', description: 'Real-world impact', priority: 'high' },
    ],
    sponsorAPIs: [
      { name: 'OpenAI', provider: 'OpenAI', description: 'GPT models', strategicValue: 'must_use' },
      { name: 'Twilio', provider: 'Twilio', description: 'SMS APIs', strategicValue: 'should_use' },
    ],
    deliverables: [],
    restrictions: [],
    deadlines: [],
    ...overrides,
  };
}

function mockResult(overrides?: Partial<InterviewResult>): InterviewResult {
  return {
    selectedPrize: null,
    selectedSponsorApis: [],
    optimizationBudget: 'balanced',
    userProjectIdea: null,
    autoGeneratedIdea: null,
    technologyPreferences: [],
    allAnswers: {},
    ...overrides,
  };
}

describe('brainstormIdeas', () => {
  it('generates exactly 20 ideas', () => {
    const result = brainstormIdeas(mockAnalysis(), mockResult());
    expect(result.generated).toHaveLength(IDEATION_POOL_SIZE);
    expect(result.generated).toHaveLength(20);
  });

  it('every idea has a title, one-liner, and score', () => {
    const result = brainstormIdeas(mockAnalysis(), mockResult());
    for (const idea of result.generated) {
      expect(idea.title).toBeTruthy();
      expect(idea.oneLiner.length).toBeGreaterThan(20);
      expect(idea.totalScore).toBeGreaterThan(0);
      expect(idea.totalScore).toBeLessThanOrEqual(100);
      expect(idea.id).toMatch(/^idea-\d{2}$/);
    }
  });

  it('one-liners are specific, not generic templates', () => {
    const result = brainstormIdeas(mockAnalysis(), mockResult());
    for (const idea of result.generated) {
      // Startup-quality concepts name a concrete mechanic, not a generic "platform".
      expect(idea.oneLiner).toMatch(/— an (innovative|impactful|technically sophisticated|compelling|fully featured|beautifully designed) ai for good idea:/);
      expect(idea.oneLiner).toContain('ai for good');
    }
  });

  it('references the top sponsor API when none selected', () => {
    const result = brainstormIdeas(mockAnalysis(), mockResult());
    for (const idea of result.generated) {
      expect(idea.oneLiner).toContain('OpenAI');
    }
  });

  it('references the user-selected sponsor API', () => {
    const result = brainstormIdeas(mockAnalysis(), mockResult({ selectedSponsorApis: ['Twilio'] }));
    for (const idea of result.generated) {
      expect(idea.oneLiner).toContain('Twilio');
    }
  });

  it('self-ranks by total score descending', () => {
    const result = brainstormIdeas(mockAnalysis(), mockResult());
    expect(result.rankedIds).toHaveLength(20);
    for (let i = 1; i < result.rankedIds.length; i++) {
      const prev = result.generated.find((g) => g.id === result.rankedIds[i - 1])!;
      const curr = result.generated.find((g) => g.id === result.rankedIds[i])!;
      expect(prev.totalScore).toBeGreaterThanOrEqual(curr.totalScore);
    }
  });

  it('shortlists the top 5 and picks the winner from it', () => {
    const result = brainstormIdeas(mockAnalysis(), mockResult());
    expect(result.shortlist).toHaveLength(IDEATION_SHORTLIST_SIZE);
    expect(result.winner.id).toBe(result.shortlist[0]!.id);
    expect(result.winner.id).toBe(result.rankedIds[0]!);
  });

  it('expands the shortlist with concept, features, wow moment, and why it wins', () => {
    const result = brainstormIdeas(mockAnalysis(), mockResult());
    for (const idea of result.shortlist) {
      expect(idea.concept.length).toBeGreaterThan(20);
      expect(idea.keyFeatures.length).toBeGreaterThanOrEqual(3);
      expect(idea.wowMoment.length).toBeGreaterThan(10);
      expect(idea.whyItWins.length).toBeGreaterThan(20);
      expect(idea.brandName.length).toBeGreaterThan(0);
    }
  });

  it('explains why the winner wins', () => {
    const result = brainstormIdeas(mockAnalysis(), mockResult());
    expect(result.rationale).toContain(result.winner.title);
    expect(result.rationale).toContain('wins the brainstorm');
    expect(result.rationale).toContain(String(result.winner.totalScore));
  });

  it('maps rationale to the top judging criterion', () => {
    const result = brainstormIdeas(mockAnalysis(), mockResult());
    expect(result.rationale).toContain('Innovation');
  });

  it('is deterministic for identical inputs', () => {
    const analysis = mockAnalysis();
    const result = mockResult();
    const a = brainstormIdeas(analysis, result);
    const b = brainstormIdeas(analysis, result);
    expect(a).toEqual(b);
  });

  it('is deterministic across repeated winner selection', () => {
    const analysis = mockAnalysis();
    const r1 = brainstormIdeas(analysis, mockResult());
    const r2 = brainstormIdeas(analysis, mockResult());
    expect(r1.winner.title).toBe(r2.winner.title);
  });

  it('produces different ideas for a different theme', () => {
    const climate = mockAnalysis({
      challenge: {
        title: 'Climate Hack',
        problemStatement: 'Build for climate action',
        theme: 'Climate Action',
        difficulty: 'advanced',
        estimatedParticipants: 150,
        organizer: 'GreenOrg',
      },
    });
    const a = brainstormIdeas(climate, mockResult());
    const b = brainstormIdeas(mockAnalysis(), mockResult());
    expect(a.winner.title).not.toBe(b.winner.title);
  });

  it('handles empty sponsor APIs and empty criteria', () => {
    const result = brainstormIdeas(
      mockAnalysis({ sponsorAPIs: [], judgingCriteria: [] }),
      mockResult(),
    );
    expect(result.generated).toHaveLength(20);
    expect(result.winner.oneLiner).toBeTruthy();
  });

  it('no idea title repeats (unique concepts)', () => {
    const result = brainstormIdeas(mockAnalysis(), mockResult());
    const titles = new Set(result.generated.map((g) => g.title));
    expect(titles.size).toBe(20);
  });
});
