import { describe, it, expect } from 'vitest';

import { brainstormIdeas } from '../../cli/ideation/idea-engine.js';
import { generateProjectIdea } from '../../cli/interview/idea-generator.js';
import { generateQuestions, runInterview } from '../../cli/interview/index.js';
import type { AskFunction } from '../../cli/interview/runner.js';
import { WinningStrategyGenerator } from '../../cli/pipeline/strategy.js';
import type { CompetitionAnalysis } from '../../cli/pipeline/types.js';

function mockAnalysis(): CompetitionAnalysis {
  return {
    analysisId: 'ca-e2e',
    challenge: {
      title: 'AI for Good Hackathon',
      problemStatement: 'Build AI solutions for social impact',
      theme: 'AI for Good',
      difficulty: 'intermediate',
      estimatedParticipants: 200,
      organizer: 'TestOrg',
    },
    judgingCriteria: [
      { name: 'Innovation', weight: 40, weightRaw: '40%', description: 'Originality', priority: 'critical' },
      { name: 'Technical Depth', weight: 30, weightRaw: '30%', description: 'Sophistication', priority: 'high' },
      { name: 'Social Impact', weight: 30, weightRaw: '30%', description: 'Impact', priority: 'high' },
    ],
    sponsorAPIs: [
      { name: 'OpenAI', provider: 'OpenAI', description: 'GPT models', strategicValue: 'must_use' },
    ],
    deliverables: [],
    restrictions: [],
    deadlines: [],
  };
}

function mockAsk(answers: Array<string | null>): AskFunction {
  let idx = 0;
  return async () => {
    const a = answers[idx];
    idx++;
    return a ?? null;
  };
}

describe('production interview flow — end to end', () => {
  it('populates ideation through the real runtime when the idea question is skipped', async () => {
    const analysis = mockAnalysis();
    const questions = generateQuestions(analysis);
    // '1' selects OpenAI sponsors, '1' picks balanced budget, null skips the
    // idea question → the runtime must auto-generate via the brainstorm engine.
    const ask = mockAsk(['1', '1', null]);

    const result = await runInterview(questions, ask, analysis);

    expect(result.userProjectIdea).toBeNull();
    expect(result.ideation).toBeTruthy();
    expect(result.ideation?.generated).toHaveLength(20);
    expect(result.ideation?.shortlist).toHaveLength(5);
    // The brainstorm winner must be one of the expanded shortlist.
    expect(result.ideation?.shortlist.some((i) => i.id === result.ideation?.winner.id)).toBe(true);
    // The runtime must have run the full product intelligence pass, whose
    // winner (re-ranked by viability/feasibility/judge sim) feeds the
    // backward-compatible autoGeneratedIdea one-liner.
    expect(result.productIntelligence).toBeTruthy();
    expect(result.autoGeneratedIdea).toBe(result.productIntelligence?.winner.oneLiner);
    expect(result.productIntelligence?.vision.oneLiner.length).toBeGreaterThan(10);
    expect(result.productIntelligence?.architecture.summary.length).toBeGreaterThan(10);
  });

  it('the strategy pipeline receives InterviewResult.ideation during normal execution', async () => {
    const analysis = mockAnalysis();
    const questions = generateQuestions(analysis);
    const ask = mockAsk(['1', '1', null]);

    const interviewResult = await runInterview(questions, ask, analysis);
    const strategy = new WinningStrategyGenerator().generate(analysis, interviewResult);

    // Blocker 2: strategy must consume the runtime-populated ideation.
    expect(strategy.ideation?.winner.id).toBe(interviewResult.ideation?.winner.id);
    expect(strategy.productIntelligence?.winner.id).toBe(interviewResult.productIntelligence?.winner.id);
    expect(strategy.brandName).toBe(interviewResult.productIntelligence?.winner.brandName);
    expect(strategy.oneLiner).toBe(interviewResult.productIntelligence?.vision.oneLiner);
    // The judge-simulated panel score replaces the heuristic estimate.
    expect(strategy.estimatedJudgeScore).toBe(interviewResult.productIntelligence!.winner.judgeSimulation.total);
  });

  it('empty interview still runs the brainstorm pipeline when analysis is provided', async () => {
    const analysis = mockAnalysis();
    const result = await runInterview([], undefined, analysis);

    expect(result.ideation).toBeTruthy();
    expect(result.ideation?.generated).toHaveLength(20);
    expect(result.autoGeneratedIdea).toBe(result.productIntelligence?.winner.oneLiner);
    expect(result.productIntelligence).toBeTruthy();
  });

  it('no analysis means no auto-generation (backward-compatible)', async () => {
    const questions = generateQuestions(mockAnalysis());
    const ask = mockAsk(['1', '1', null]);

    const result = await runInterview(questions, ask);

    expect(result.ideation).toBeNull();
    expect(result.productIntelligence).toBeNull();
    expect(result.autoGeneratedIdea).toBeNull();
  });

  it('user-supplied idea bypasses auto-generation (backward-compatible)', async () => {
    const analysis = mockAnalysis();
    const questions = generateQuestions(analysis);
    const ask = mockAsk(['1', '1', 'My custom idea']);

    const result = await runInterview(questions, ask, analysis);

    expect(result.userProjectIdea).toBe('My custom idea');
    expect(result.ideation).toBeNull();
    expect(result.autoGeneratedIdea).toBeNull();
  });
});

describe('single canonical ideation engine', () => {
  it('interview entry point delegates to the ideation engine', () => {
    const analysis = mockAnalysis();
    const result = runInterviewStub();

    const oneLiner = generateProjectIdea(analysis, result);
    const canonical = brainstormIdeas(analysis, result).winner.oneLiner;

    // Same engine, same output — there is exactly one canonical implementation.
    expect(oneLiner).toBe(canonical);
  });

  it('produces identical ideas deterministically across runs', async () => {
    const analysis = mockAnalysis();
    const questions = generateQuestions(analysis);
    const a = await runInterview(questions, mockAsk(['1', '1', null]), analysis);
    const b = await runInterview(questions, mockAsk(['1', '1', null]), analysis);

    expect(a.ideation?.winner.id).toBe(b.ideation?.winner.id);
    expect(a.ideation?.winner.oneLiner).toBe(b.ideation?.winner.oneLiner);
    expect(a.productIntelligence?.winner.judgeSimulation.total).toBe(b.productIntelligence?.winner.judgeSimulation.total);
  });
});

function runInterviewStub(): Parameters<typeof generateProjectIdea>[1] {
  return {
    selectedPrize: null,
    selectedSponsorApis: [],
    optimizationBudget: 'balanced',
    userProjectIdea: null,
    autoGeneratedIdea: null,
    technologyPreferences: [],
    allAnswers: {},
  };
}
