import { describe, it, expect } from 'vitest';

import { generateProjectIdea } from '../../cli/interview/idea-generator.js';
import type { CompetitionAnalysis } from '../../cli/pipeline/types.js';
import type { InterviewResult } from '../../cli/interview/types.js';

function mockAnalysis(overrides?: Partial<CompetitionAnalysis>): CompetitionAnalysis {
  return {
    analysisId: 'ca-test',
    challenge: {
      title: 'AI for Good Hackathon',
      problemStatement: 'Build AI solutions for social impact',
      theme: 'AI for Good',
      difficulty: 'intermediate',
      estimatedParticipants: 200,
      organizer: 'TestOrg',
    },
    judgingCriteria: [
      { name: 'Innovation', weight: 40, weightRaw: '40%', description: 'Originality', priority: 'critical' },
      { name: 'Technical Depth', weight: 30, weightRaw: '30%', description: 'Sophistication', priority: 'high' },
      { name: 'Social Impact', weight: 30, weightRaw: '30%', description: 'Real-world impact', priority: 'high' },
    ],
    sponsorAPIs: [
      { name: 'OpenAI', provider: 'OpenAI', description: 'GPT models', strategicValue: 'must_use' },
      { name: 'Twilio', provider: 'Twilio', description: 'SMS APIs', strategicValue: 'should_use' },
    ],
    deliverables: [],
    restrictions: [],
    deadlines: [],
    ...overrides,
  };
}

function mockResult(overrides?: Partial<InterviewResult>): InterviewResult {
  return {
    selectedPrize: null,
    selectedSponsorApis: [],
    optimizationBudget: 'balanced',
    userProjectIdea: null,
    autoGeneratedIdea: null,
    technologyPreferences: [],
    allAnswers: {},
    ...overrides,
  };
}

describe('generateProjectIdea', () => {
  it('uses top judging criterion as focus area', () => {
    const analysis = mockAnalysis();
    const result = mockResult();
    const idea = generateProjectIdea(analysis, result);

    expect(idea).toBeTruthy();
    expect(idea.length).toBeGreaterThan(20);
    expect(idea).toContain('ai for good');
  });

  it('references highest-priority sponsor API when none selected', () => {
    const analysis = mockAnalysis();
    const result = mockResult({ selectedSponsorApis: [] });
    const idea = generateProjectIdea(analysis, result);

    expect(idea).toContain('OpenAI');
  });

  it('references user-selected sponsor API when provided', () => {
    const analysis = mockAnalysis();
    const result = mockResult({ selectedSponsorApis: ['Twilio'] });
    const idea = generateProjectIdea(analysis, result);

    expect(idea).toContain('Twilio');
  });

  it('generates innovation-focused idea for highest weighted criterion', () => {
    const analysis = mockAnalysis();
    const result = mockResult({ selectedSponsorApis: ['OpenAI'] });
    const idea = generateProjectIdea(analysis, result);

    expect(idea).toContain('innovative');
    expect(idea).toContain('OpenAI');
    expect(idea).toContain('ai for good');
  });

  it('generates technology-focused idea when technical criterion is top', () => {
    const analysis = mockAnalysis({
      judgingCriteria: [
        { name: 'Technical Depth', weight: 50, weightRaw: '50%', description: 'Sophistication', priority: 'critical' },
        { name: 'Innovation', weight: 30, weightRaw: '30%', description: 'Originality', priority: 'high' },
        { name: 'Impact', weight: 20, weightRaw: '20%', description: 'Reach', priority: 'medium' },
      ],
    });
    const result = mockResult({ selectedSponsorApis: ['OpenAI'] });
    const idea = generateProjectIdea(analysis, result);

    expect(idea).toContain('technically sophisticated');
    expect(idea).toContain('OpenAI');
  });

  it('generates impact-focused idea when impact criterion is top', () => {
    const analysis = mockAnalysis({
      judgingCriteria: [
        { name: 'Social Impact', weight: 50, weightRaw: '50%', description: 'Real-world impact', priority: 'critical' },
        { name: 'Innovation', weight: 30, weightRaw: '30%', description: 'Originality', priority: 'high' },
        { name: 'Technical Depth', weight: 20, weightRaw: '20%', description: 'Sophistication', priority: 'medium' },
      ],
    });
    const result = mockResult({ selectedSponsorApis: [] });
    const idea = generateProjectIdea(analysis, result);

    expect(idea).toContain('impactful');
    expect(idea).toContain('OpenAI');
  });

  it('uses theme from challenge analysis', () => {
    const analysis = mockAnalysis({
      challenge: {
        title: 'Climate Hack',
        problemStatement: 'Build for climate',
        theme: 'Climate Action',
        difficulty: 'advanced',
        estimatedParticipants: 150,
        organizer: 'GreenOrg',
      },
    });
    const result = mockResult({ selectedSponsorApis: ['OpenAI'] });
    const idea = generateProjectIdea(analysis, result);

    expect(idea).toContain('climate action');
  });

  it('produces same output deterministically for same inputs', () => {
    const analysis = mockAnalysis();
    const result = mockResult();

    const idea1 = generateProjectIdea(analysis, result);
    const idea2 = generateProjectIdea(analysis, result);

    expect(idea1).toBe(idea2);
  });

  it('handles empty sponsor APIs', () => {
    const analysis = mockAnalysis({ sponsorAPIs: [] });
    const result = mockResult({ selectedSponsorApis: [] });
    const idea = generateProjectIdea(analysis, result);

    expect(idea).toBeTruthy();
    expect(idea).toContain('ai for good');
  });
});
