import { describe, it, expect } from 'vitest';

import { runInterview } from '../../cli/interview/runner.js';
import type { AskFunction } from '../../cli/interview/runner.js';
import type { InterviewQuestion } from '../../cli/interview/types.js';
import type { CompetitionAnalysis } from '../../cli/pipeline/types.js';

function mockAsk(answers: Array<string | null>): AskFunction {
  let idx = 0;
  return async () => {
    const a = answers[idx];
    idx++;
    return a ?? null;
  };
}

function testQuestions(): InterviewQuestion[] {
  return [
    {
      id: 'q_sponsors',
      text: 'Which sponsor APIs?',
      category: 'sponsor_selection',
      options: [
        { value: 'OpenAI', label: 'OpenAI', description: 'GPT models', influences: { sponsorApis: ['OpenAI'], technologyPreference: ['python'] } },
        { value: 'Twilio', label: 'Twilio', description: 'SMS APIs', influences: { sponsorApis: ['Twilio'], technologyPreference: ['express'] } },
      ],
      required: false,
      dependsOn: [],
      skipLabel: 'Skip sponsors',
    },
    {
      id: 'q_budget',
      text: 'Optimization budget?',
      category: 'optimization',
      options: [
        { value: 'minimal', label: 'Minimal', description: 'Core only', influences: { optimizationBudget: 'minimal' as const } },
        { value: 'balanced', label: 'Balanced', description: 'Good mix', influences: { optimizationBudget: 'balanced' as const } },
        { value: 'aggressive', label: 'Aggressive', description: 'Go big', influences: { optimizationBudget: 'aggressive' as const } },
      ],
      required: true,
      dependsOn: [],
    },
    {
      id: 'q_idea',
      text: 'Project idea?',
      category: 'project_idea',
      options: [],
      required: false,
      dependsOn: [],
      skipLabel: 'Auto-generate',
    },
  ];
}

function mockAnalysis(): CompetitionAnalysis {
  return {
    analysisId: 'ca-test',
    challenge: { title: 'Test Hackathon', problemStatement: 'Build something', theme: 'Innovation', difficulty: 'intermediate', estimatedParticipants: 100, organizer: 'Test' },
    judgingCriteria: [{ name: 'Innovation', weight: 100, weightRaw: '100%', description: 'Originality', priority: 'critical' }],
    sponsorAPIs: [{ name: 'OpenAI', provider: 'OpenAI', description: 'GPT', strategicValue: 'must_use' }],
    deliverables: [],
    restrictions: [],
    deadlines: [],
  };
}

describe('runInterview', () => {
  it('returns empty result for no questions', async () => {
    const result = await runInterview([]);
    expect(result.selectedPrize).toBeNull();
    expect(result.selectedSponsorApis).toEqual([]);
    expect(result.userProjectIdea).toBeNull();
    expect(result.autoGeneratedIdea).toBeNull();
  });

  it('collects single-select answers', async () => {
    const questions = testQuestions();
    const ask = mockAsk(['2', '3']);

    const result = await runInterview(questions, ask);

    expect(result.selectedSponsorApis).not.toContain('OpenAI');
    expect(result.selectedSponsorApis).toContain('Twilio');
    expect(result.optimizationBudget).toBe('aggressive');
    expect(result.userProjectIdea).toBeNull();
  });

  it('handles skip for all questions', async () => {
    const questions = testQuestions();
    const ask = mockAsk([null, null, null]);

    const result = await runInterview(questions, ask);

    expect(result.selectedSponsorApis).toEqual([]);
    expect(result.optimizationBudget).toBe('balanced');
    expect(result.userProjectIdea).toBeNull();
    expect(result.allAnswers.q_sponsors).toBeNull();
    expect(result.allAnswers.q_budget).toBeNull();
    expect(result.allAnswers.q_idea).toBeNull();
  });

  it('handles S for skip', async () => {
    const questions = testQuestions();
    const ask = mockAsk(['s', 's']);

    const result = await runInterview(questions, ask);

    expect(result.selectedSponsorApis).toEqual([]);
    expect(result.optimizationBudget).toBe('balanced');
    expect(result.userProjectIdea).toBeNull();
  });

  it('supports multi-select for sponsor APIs', async () => {
    const questions = testQuestions();
    const ask = mockAsk(['1,2', '1']);

    const result = await runInterview(questions, ask);

    expect(result.selectedSponsorApis).toEqual(['OpenAI', 'Twilio']);
    expect(result.technologyPreferences).toContain('python');
    expect(result.technologyPreferences).toContain('express');
  });

  it('collects technology preferences from selected sponsors', async () => {
    const questions = testQuestions();
    const ask = mockAsk(['1', '2']);

    const result = await runInterview(questions, ask);

    expect(result.technologyPreferences).toContain('python');
    expect(result.technologyPreferences).not.toContain('express');
  });

  it('allAnswers contains all question IDs', async () => {
    const questions = testQuestions();
    const ask = mockAsk([null, '2', null]);

    const result = await runInterview(questions, ask);

    expect(Object.keys(result.allAnswers)).toHaveLength(3);
    expect(result.allAnswers.q_sponsors).toBeNull();
    expect(result.allAnswers.q_budget).toBe('balanced');
    expect(result.allAnswers.q_idea).toBeNull();
  });

  it('deduplicates multi-select values', async () => {
    const questions = testQuestions();
    const ask = mockAsk(['1,1,2', '1']);

    const result = await runInterview(questions, ask);

    expect(result.selectedSponsorApis).toEqual(['OpenAI', 'Twilio']);
  });

  it('auto-generates idea when project idea skipped with analysis', async () => {
    const questions = testQuestions();
    const ask = mockAsk(['1', '2']);
    const analysis = mockAnalysis();

    const result = await runInterview(questions, ask, analysis);

    expect(result.userProjectIdea).toBeNull();
    expect(result.autoGeneratedIdea).toBeTruthy();
    expect(result.autoGeneratedIdea).toContain('OpenAI');
  });

  it('does not auto-generate when no analysis provided', async () => {
    const questions = testQuestions();
    const ask = mockAsk(['1', '2']);

    const result = await runInterview(questions, ask);

    expect(result.autoGeneratedIdea).toBeNull();
  });

  it('auto-generates idea when questions array empty with analysis', async () => {
    const analysis = mockAnalysis();
    const result = await runInterview([], undefined, analysis);

    expect(result.autoGeneratedIdea).toBeTruthy();
  });

  it('returns null autoGeneratedIdea when user answers project idea', async () => {
    const questions = testQuestions();
    const ask = mockAsk(['1', '2', 'My custom idea']);
    const analysis = mockAnalysis();

    const result = await runInterview(questions, ask, analysis);

    expect(result.userProjectIdea).toBe('My custom idea');
    expect(result.autoGeneratedIdea).toBeNull();
  });
});
