import { describe, it, expect } from 'vitest';

import type {
  InterviewQuestion,
  InterviewOption,
  InterviewInfluence,
  InterviewState,
  InterviewResult,
  QuestionCategory,
  OptimizationBudget,
} from '../../cli/interview/types.js';

describe('Interview Types', () => {
  it('creates an interview question with all fields', () => {
    const option: InterviewOption = {
      value: 'prize_1',
      label: 'Best AI Hack',
      description: 'Grand prize for AI-powered projects',
      influences: {
        prize: 'Best AI Hack',
        sponsorApis: ['openai'],
        optimizationBudget: 'aggressive',
      },
    };

    const question: InterviewQuestion = {
      id: 'q_prize',
      text: 'Which prize track are you targeting?',
      category: 'prize_selection',
      options: [option],
      required: true,
      dependsOn: [],
    };

    expect(question.id).toBe('q_prize');
    expect(question.category).toBe('prize_selection');
    expect(question.options).toHaveLength(1);
    expect(question.options[0]!.value).toBe('prize_1');
    expect(question.options[0]!.influences.prize).toBe('Best AI Hack');
    expect(question.options[0]!.influences.optimizationBudget).toBe('aggressive');
    expect(question.required).toBe(true);
    expect(question.dependsOn).toEqual([]);
  });

  it('creates a sponsor selection question with multiple options', () => {
    const options: InterviewOption[] = [
      {
        value: 'openai',
        label: 'OpenAI API',
        description: 'GPT-4o for AI features',
        influences: { sponsorApis: ['openai'] },
      },
      {
        value: 'twilio',
        label: 'Twilio SMS',
        description: 'SMS notifications',
        influences: { sponsorApis: ['twilio'] },
      },
    ];

    const question: InterviewQuestion = {
      id: 'q_sponsors',
      text: 'Which sponsor APIs do you want to use?',
      category: 'sponsor_selection',
      options,
      required: false,
      dependsOn: [],
      skipLabel: 'Skip sponsor APIs',
    };

    expect(question.options).toHaveLength(2);
    expect(question.skipLabel).toBe('Skip sponsor APIs');
    expect(question.options[1]!.influences.sponsorApis).toEqual(['twilio']);
  });

  it('creates an optimization budget question', () => {
    const budgets: OptimizationBudget[] = ['minimal', 'balanced', 'aggressive'];

    const options: InterviewOption[] = budgets.map((b) => ({
      value: b,
      label: b.charAt(0).toUpperCase() + b.slice(1),
      description: `Optimize for ${b} effort`,
      influences: { optimizationBudget: b },
    }));

    const question: InterviewQuestion = {
      id: 'q_budget',
      text: 'What is your optimization budget?',
      category: 'optimization',
      options,
      required: true,
      dependsOn: [],
    };

    expect(question.options).toHaveLength(3);
    expect(question.options[0]!.influences.optimizationBudget).toBe('minimal');
    expect(question.options[2]!.influences.optimizationBudget).toBe('aggressive');
  });

  it('creates a project idea question with skip support', () => {
    const question: InterviewQuestion = {
      id: 'q_idea',
      text: 'Do you have a project idea?',
      category: 'project_idea',
      options: [
        {
          value: 'my_idea',
          label: 'Yes, I have an idea',
          description: 'Describe your project idea',
          influences: { projectIdea: 'A social platform for hackathon teams' },
        },
      ],
      required: false,
      dependsOn: [],
    };

    expect(question.category).toBe('project_idea');
    expect(question.options[0]!.influences.projectIdea).toBeTruthy();
  });

  it('tracks interview state transitions', () => {
    const initial: InterviewState = {
      currentQuestionIndex: 0,
      answers: {},
      skipped: [],
      completed: false,
    };

    expect(initial.completed).toBe(false);
    expect(initial.currentQuestionIndex).toBe(0);

    const answered: InterviewState = {
      ...initial,
      currentQuestionIndex: 1,
      answers: { q_prize: 'prize_1' },
    };

    expect(answered.answers.q_prize).toBe('prize_1');
    expect(answered.currentQuestionIndex).toBe(1);
    expect(answered.skipped).toHaveLength(0);

    const skipped: InterviewState = {
      ...answered,
      currentQuestionIndex: 2,
      answers: { ...answered.answers, q_idea: null },
      skipped: ['q_idea'],
    };

    expect(skipped.skipped).toContain('q_idea');
    expect(skipped.answers.q_idea).toBeNull();
  });

  it('holds interview result with all fields', () => {
    const result: InterviewResult = {
      selectedPrize: 'Best AI Hack',
      selectedSponsorApis: ['openai', 'twilio'],
      optimizationBudget: 'balanced',
      userProjectIdea: 'My awesome project',
      autoGeneratedIdea: null,
      technologyPreferences: ['nextjs', 'tailwind'],
      allAnswers: { q_prize: 'Best AI Hack', q_budget: 'balanced' },
    };

    expect(result.selectedPrize).toBe('Best AI Hack');
    expect(result.selectedSponsorApis).toHaveLength(2);
    expect(result.optimizationBudget).toBe('balanced');
    expect(result.userProjectIdea).toBe('My awesome project');
    expect(result.autoGeneratedIdea).toBeNull();
    expect(result.technologyPreferences).toContain('nextjs');
    expect(result.allAnswers.q_prize).toBe('Best AI Hack');
  });

  it('produces interview result with auto-generated idea', () => {
    const result: InterviewResult = {
      selectedPrize: null,
      selectedSponsorApis: [],
      optimizationBudget: 'minimal',
      userProjectIdea: null,
      autoGeneratedIdea: 'An AI-powered dashboard for tracking hackathon submissions',
      technologyPreferences: [],
      allAnswers: {},
    };

    expect(result.selectedPrize).toBeNull();
    expect(result.autoGeneratedIdea).toBeTruthy();
    expect(result.autoGeneratedIdea).toContain('AI');
  });
});
