import { describe, it, expect } from 'vitest';
import * as path from 'node:path';
import * as fs from 'node:fs';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';

import type { InterviewResult } from '../../cli/interview/types.js';
import { WinningStrategyGenerator } from '../../cli/pipeline/strategy.js';
import type { CompetitionAnalysis } from '../../cli/pipeline/types.js';
import { buildCodeGenContext } from '../../cli/pipeline/strategy-adapter.js';
import { runProductIntelligence } from '../../cli/product-intelligence/orchestrator.js';

function mockAnalysis(): CompetitionAnalysis {
  return {
    analysisId: 'ca-scaffold',
    challenge: {
      title: 'AI for Good Hackathon',
      problemStatement: 'Build AI solutions for social impact',
      theme: 'AI for Good',
      difficulty: 'intermediate',
      estimatedParticipants: 200,
      organizer: 'TestOrg',
    },
    judgingCriteria: [
      { name: 'Innovation', weight: 40, weightRaw: '40%', description: 'Originality', priority: 'critical' },
      { name: 'Technical Depth', weight: 30, weightRaw: '30%', description: 'Sophistication', priority: 'high' },
      { name: 'Social Impact', weight: 30, weightRaw: '30%', description: 'Impact', priority: 'high' },
    ],
    sponsorAPIs: [
      { name: 'OpenAI', provider: 'OpenAI', description: 'GPT models', strategicValue: 'must_use' },
    ],
    deliverables: [],
    restrictions: [],
    deadlines: [],
  };
}

async function buildScaffoldWithPI() {
  const InternetHackathonOrchestrator = (await import('../../benchmarks/internet-hackathon-orchestrator.js')).InternetHackathonOrchestrator;
  const projectDir = path.join(tmpdir(), `hag-pi-${randomUUID().slice(0, 8)}`);
  fs.mkdirSync(path.join(projectDir, 'node_modules'), { recursive: true });

  const analysis = mockAnalysis();
  const pi = runProductIntelligence(analysis, null);
  const interviewResult: InterviewResult = {
    selectedPrize: null,
    selectedSponsorApis: [],
    optimizationBudget: 'balanced',
    userProjectIdea: null,
    autoGeneratedIdea: pi.winner.oneLiner,
    ideation: pi.brainstorm,
    productIntelligence: pi,
    technologyPreferences: [],
    allAnswers: {},
  };
  const strategy = new WinningStrategyGenerator().generate(analysis, interviewResult);
  const ctx = buildCodeGenContext(analysis, strategy);

  const orch = new InternetHackathonOrchestrator(projectDir, path.join(projectDir, '.hackagent'), 42, undefined);
  orch.setDevpostData({
    title: 'AI for Good Hackathon',
    problemStatement: analysis.challenge.problemStatement,
    judgingCriteria: analysis.judgingCriteria.map(c => c.name),
    constraints: [],
    recommendedStack: ['Next.js'],
    submissionRequirements: [],
    rawText: '',
  });
  orch.setStrategyContext(ctx);
  const plan = await orch.createExecutionPlan(
    { title: 'AI for Good Hackathon', problemStatement: analysis.challenge.problemStatement, judgingCriteria: analysis.judgingCriteria.map(c => c.name), constraints: [], recommendedStack: ['Next.js'], submissionRequirements: [], rawText: '' },
    [],
  );
  const files = await (orch as unknown as {
    generateScaffoldFiles(plan: unknown): Promise<Array<{ path: string; content: string }>>;
  }).generateScaffoldFiles(plan);

  return { files, pi, ctx, projectDir };
}

describe('Product Intelligence → generated scaffold', () => {
  it('carries the PI brand name and one-liner into the generated landing page', async () => {
    const { files, pi, ctx } = await buildScaffoldWithPI();

    const page = files.find(f => f.path === 'src/app/page.tsx')!;
    const layout = files.find(f => f.path === 'src/app/layout.tsx')!;
    const readme = files.find(f => f.path === 'README.md')!;
    expect(page).toBeTruthy();
    expect(layout).toBeTruthy();
    expect(readme).toBeTruthy();

    // Branding: the startup-quality brand name titles the landing page.
    expect(page.content).toContain(pi.winner.brandName);
    expect(layout.content).toContain(pi.winner.brandName);
    // The PI one-liner becomes the hero tagline and metadata description.
    expect(page.content).toContain(ctx.oneLiner.slice(0, 60));
    expect(layout.content).toContain(ctx.oneLiner.slice(0, 60));
    // README leads with the brand.
    expect(readme.content).toContain(pi.winner.brandName);
  });

  it('falls back to the slug title when no PI strategy context is set', async () => {
    const InternetHackathonOrchestrator = (await import('../../benchmarks/internet-hackathon-orchestrator.js')).InternetHackathonOrchestrator;
    const projectDir = path.join(tmpdir(), `hag-nopi-${randomUUID().slice(0, 8)}`);
    fs.mkdirSync(path.join(projectDir, 'node_modules'), { recursive: true });

    const orch = new InternetHackathonOrchestrator(projectDir, path.join(projectDir, '.hackagent'), 42, undefined);
    orch.setDevpostData({ title: 'AI for Good Hackathon', problemStatement: 'Problem', judgingCriteria: [], constraints: [], recommendedStack: ['Next.js'], submissionRequirements: [], rawText: '' });
    const plan = await orch.createExecutionPlan({ title: 'AI for Good Hackathon', problemStatement: 'Problem', judgingCriteria: [], constraints: [], recommendedStack: ['Next.js'], submissionRequirements: [], rawText: '' }, []);
    const files = await (orch as unknown as {
      generateScaffoldFiles(plan: unknown): Promise<Array<{ path: string; content: string }>>;
    }).generateScaffoldFiles(plan);

    const page = files.find(f => f.path === 'src/app/page.tsx')!;
    // No brand context → deterministic slug-derived title, unchanged behavior.
    expect(page.content).not.toContain('Ember');
    expect(page.content).toContain('Ai For Good Hackathon');
  });
});
