import { describe, it, expect } from 'vitest';

import type { InterviewResult } from '../../cli/interview/types.js';
import type { CompetitionAnalysis } from '../../cli/pipeline/types.js';
import { runProductIntelligence } from '../../cli/product-intelligence/orchestrator.js';

function mockAnalysis(overrides?: Partial<CompetitionAnalysis>): CompetitionAnalysis {
  return {
    analysisId: 'ca-pi',
    challenge: {
      title: 'AI for Good Hackathon',
      problemStatement: 'Build AI solutions for social impact',
      theme: 'AI for Good',
      difficulty: 'intermediate',
      estimatedParticipants: 200,
      organizer: 'TestOrg',
    },
    judgingCriteria: [
      { name: 'Innovation', weight: 40, weightRaw: '40%', description: 'Originality', priority: 'critical' },
      { name: 'Technical Depth', weight: 30, weightRaw: '30%', description: 'Sophistication', priority: 'high' },
      { name: 'Social Impact', weight: 30, weightRaw: '30%', description: 'Real-world impact', priority: 'high' },
    ],
    sponsorAPIs: [
      { name: 'OpenAI', provider: 'OpenAI', description: 'GPT models', strategicValue: 'must_use' },
      { name: 'Twilio', provider: 'Twilio', description: 'SMS APIs', strategicValue: 'should_use' },
    ],
    deliverables: [],
    restrictions: [],
    deadlines: [],
    ...overrides,
  };
}

function mockResult(overrides?: Partial<InterviewResult>): InterviewResult {
  return {
    selectedPrize: null,
    selectedSponsorApis: [],
    optimizationBudget: 'balanced',
    userProjectIdea: null,
    autoGeneratedIdea: null,
    technologyPreferences: [],
    allAnswers: {},
    ...overrides,
  };
}

describe('runProductIntelligence', () => {
  it('extracts judging priorities sorted by weight', () => {
    const pi = runProductIntelligence(mockAnalysis(), mockResult());
    expect(pi.judgingPriorities.length).toBe(3);
    expect(pi.judgingPriorities[0]!.name).toBe('Innovation');
    expect(pi.judgingPriorities[0]!.weight).toBeGreaterThanOrEqual(pi.judgingPriorities[1]!.weight);
    expect(pi.judgingPriorities[0]!.approach.length).toBeGreaterThan(10);
    expect(pi.judgingPriorities[0]!.focus).toBe('wow');
  });

  it('extracts sponsor opportunities with opportunity and risk', () => {
    const pi = runProductIntelligence(mockAnalysis(), mockResult());
    expect(pi.sponsorOpportunities.length).toBe(2);
    const openai = pi.sponsorOpportunities.find((s) => s.name === 'OpenAI')!;
    expect(openai.strategicValue).toBe('must_use');
    expect(openai.opportunity.length).toBeGreaterThan(10);
    expect(openai.risk).toContain('Required');
  });

  it('runs the 20-idea brainstorm and deep-evaluates the top 5', () => {
    const pi = runProductIntelligence(mockAnalysis(), mockResult());
    expect(pi.brainstorm.generated).toHaveLength(20);
    expect(pi.evaluatedShortlist).toHaveLength(5);
    for (const idea of pi.evaluatedShortlist) {
      expect(idea.viability.total).toBeGreaterThanOrEqual(0);
      expect(idea.feasibilityAnalysis.estimateHours).toBeGreaterThan(0);
      expect(idea.judgeSimulation.judges).toHaveLength(3);
      expect(idea.selfCritique.length).toBeGreaterThan(0);
      expect(idea.finalScore).toBeGreaterThan(0);
      expect(idea.finalScore).toBeLessThanOrEqual(100);
    }
  });

  it('picks the winner as the highest-finalScore shortlist entry', () => {
    const pi = runProductIntelligence(mockAnalysis(), mockResult());
    expect(pi.winner.id).toBe(pi.evaluatedShortlist[0]!.id);
    const maxScore = Math.max(...pi.evaluatedShortlist.map((i) => i.finalScore));
    expect(pi.winner.finalScore).toBe(maxScore);
  });

  it('selects a winner different from the raw ideation winner when deep eval prefers another', () => {
    // Force a deterministic scenario where judge/viability shift the pick:
    // both winners are valid, but the final pick must be self-consistent.
    const pi = runProductIntelligence(mockAnalysis(), mockResult());
    expect(pi.winner.oneLiner).toBeTruthy();
    expect(pi.evaluatedShortlist.map((i) => i.title)).toContain(pi.winner.title);
  });

  it('produces a complete product vision before code generation', () => {
    const pi = runProductIntelligence(mockAnalysis(), mockResult());
    const v = pi.vision;
    expect(v.visionStatement.length).toBeGreaterThan(20);
    expect(v.oneLiner.length).toBeGreaterThan(10);
    expect(v.targetUser).toBeTruthy();
    expect(v.problem.length).toBeGreaterThan(20);
    expect(v.whyNow.length).toBeGreaterThan(20);
    expect(v.coreUserJourney.length).toBeGreaterThanOrEqual(4);
    expect(v.mvpScope.length).toBeGreaterThanOrEqual(4);
    expect(v.wowMoment.length).toBeGreaterThan(10);
    expect(v.differentiator.length).toBeGreaterThan(20);
    expect(v.architectureSummary.length).toBeGreaterThan(10);
    expect(v.demoStrategy.length).toBeGreaterThan(30);
    expect(v.successMetrics.length).toBeGreaterThanOrEqual(3);
    expect(v.risks.length).toBeGreaterThan(0);
  });

  it('produces an architecture plan with stack, modules and data model', () => {
    const pi = runProductIntelligence(mockAnalysis(), mockResult());
    const a = pi.architecture;
    expect(a.summary.length).toBeGreaterThan(20);
    expect(a.recommendedStack.length).toBeGreaterThanOrEqual(3);
    expect(a.modules.length).toBeGreaterThanOrEqual(3);
    expect(a.dataModel.length).toBeGreaterThan(0);
    expect(a.apiSurfaces.length).toBeGreaterThan(0);
    expect(a.deployment.length).toBeGreaterThan(0);
    expect(a.sponsorIntegrations).toContain('OpenAI');
  });

  it('explains why the winner won', () => {
    const pi = runProductIntelligence(mockAnalysis(), mockResult());
    expect(pi.selectionRationale).toContain(pi.winner.title);
    expect(pi.selectionRationale).toContain('wins the product intelligence pass');
  });

  it('judge simulation scores every real criterion', () => {
    const pi = runProductIntelligence(mockAnalysis(), mockResult());
    for (const judge of pi.winner.judgeSimulation.judges) {
      expect(judge.scores).toHaveLength(3);
      for (const s of judge.scores) {
        expect(s.score).toBeGreaterThanOrEqual(1);
        expect(s.score).toBeLessThanOrEqual(10);
        expect(s.note.length).toBeGreaterThan(5);
      }
    }
    expect(pi.winner.judgeSimulation.topCriterion).toBeTruthy();
    expect(pi.winner.judgeSimulation.weakestCriterion).toBeTruthy();
  });

  it('is deterministic for identical inputs', () => {
    const analysis = mockAnalysis();
    const result = mockResult();
    expect(runProductIntelligence(analysis, result)).toEqual(runProductIntelligence(analysis, result));
  });

  it('handles empty criteria and sponsors', () => {
    const pi = runProductIntelligence(
      mockAnalysis({ sponsorAPIs: [], judgingCriteria: [] }),
      mockResult(),
    );
    expect(pi.evaluatedShortlist).toHaveLength(5);
    expect(pi.vision.oneLiner).toBeTruthy();
    expect(pi.architecture.sponsorIntegrations).toEqual([]);
  });

  it('scopes feasibility estimate to the optimization budget', () => {
    const analysis = mockAnalysis();
    const minimal = runProductIntelligence(analysis, mockResult({ optimizationBudget: 'minimal' }));
    const aggressive = runProductIntelligence(analysis, mockResult({ optimizationBudget: 'aggressive' }));
    const winnerId = minimal.winner.id;
    const minIdea = minimal.evaluatedShortlist.find((i) => i.id === winnerId)!;
    const aggIdea = aggressive.evaluatedShortlist.find((i) => i.id === winnerId)!;
    expect(minIdea.feasibilityAnalysis.estimateHours).toBeLessThanOrEqual(aggIdea.feasibilityAnalysis.estimateHours);
  });
});
