import { describe, it, expect } from 'vitest';

import type { InterviewResult } from '../../cli/interview/types.js';
import {
  assembleGenerationPrompt,
  estimateTokens,
  formatGenerationPromptDiagnostics,
  type GenerationPromptInput,
} from '../../cli/pipeline/prompt-assembler.js';
import { buildCodeGenContext, renderStrategyPromptBlock } from '../../cli/pipeline/strategy-adapter.js';
import { WinningStrategyGenerator } from '../../cli/pipeline/strategy.js';
import type { CompetitionAnalysis } from '../../cli/pipeline/types.js';
import { runProductIntelligence } from '../../cli/product-intelligence/orchestrator.js';

function mockAnalysis(): CompetitionAnalysis {
  return {
    analysisId: 'ca-prompt-audit',
    challenge: {
      title: 'AI for Good Hackathon',
      problemStatement: 'Build AI solutions for social impact',
      theme: 'AI for Good',
      difficulty: 'intermediate',
      estimatedParticipants: 200,
      organizer: 'TestOrg',
    },
    judgingCriteria: [
      { name: 'Innovation', weight: 40, weightRaw: '40%', description: 'Originality', priority: 'critical' },
      { name: 'Technical Depth', weight: 30, weightRaw: '30%', description: 'Sophistication', priority: 'high' },
      { name: 'Social Impact', weight: 30, weightRaw: '30%', description: 'Impact', priority: 'high' },
    ],
    sponsorAPIs: [
      { name: 'OpenAI', provider: 'OpenAI', description: 'GPT models', strategicValue: 'must_use' },
    ],
    deliverables: [],
    restrictions: [],
    deadlines: [],
  };
}

/** Real runtime path: PI pass → strategy → codegen context → strategy block. */
function buildStrategyContext() {
  const analysis = mockAnalysis();
  const pi = runProductIntelligence(analysis, null);
  const interviewResult: InterviewResult = {
    selectedPrize: null,
    selectedSponsorApis: [],
    optimizationBudget: 'balanced',
    userProjectIdea: null,
    autoGeneratedIdea: pi.winner.oneLiner,
    ideation: pi.brainstorm,
    productIntelligence: pi,
    technologyPreferences: [],
    allAnswers: {},
  };
  const strategy = new WinningStrategyGenerator().generate(analysis, interviewResult);
  const ctx = buildCodeGenContext(analysis, strategy);
  return { analysis, pi, strategy, ctx, strategyBlock: renderStrategyPromptBlock(ctx) };
}

function baseInput(overrides: Partial<GenerationPromptInput> = {}): GenerationPromptInput {
  return {
    projectName: 'hack-project',
    problemStatement: 'Reduce food waste in supply chains',
    submissionRequirements: [],
    sponsorApis: [],
    judgingCriteria: [],
    featurePriority: [],
    keyPages: [],
    differentiators: [],
    optimizationBudget: '',
    rawConstraints: [],
    techStackDisplay: 'Frontend: Next.js, Backend: Node.js, Database: SQLite, Deployment: Vercel',
    requiredTechs: [],
    strategyBlock: '',
    packageVersions: 'For package.json use these exact versions: next@^14.2.0, react@^18.3.1',
    taskDescription: 'Generate the landing page',
    fileType: 'frontend',
    specificTask: 'Hero section',
    ...overrides,
  };
}

describe('assembleGenerationPrompt — Product Intelligence path (strategy block present)', () => {
  const { ctx, strategyBlock } = buildStrategyContext();
  const assembly = assembleGenerationPrompt(baseInput({
    strategyBlock,
    projectName: ctx.strategyName,
    systemPrompt: 'You are an expert code generator. Generate code that compiles without errors.',
    // The orchestrator feeds these from the codegen context / generation input;
    // all are fields the STRATEGY block also carries, so each must be deduped.
    sponsorApis: ctx.sponsorApis,
    judgingCriteria: ctx.judgingCriteria,
    featurePriority: ctx.taskOrder.map(f => f.feature),
    keyPages: ctx.uiScaffold.keyScreens,
    differentiators: ['test differentiator'],
  }));

  it('carries every PI planning artifact into the prompt', () => {
    const p = assembly.userPrompt;
    expect(p).toContain(`Winning idea: ${ctx.productIntelligence!.winnerTitle}`);
    expect(p).toContain(`Vision: ${ctx.productIntelligence!.visionStatement}`);
    expect(p).toContain(`Target users: ${ctx.productIntelligence!.targetUser}`);
    expect(p).toContain(`Wow moment: ${ctx.productIntelligence!.wowMoment}`);
    expect(p).toContain('MVP scope:');
    expect(p).toContain('Differentiator: ');
    expect(p).toContain('Demo strategy:');
    expect(p).toContain(`Architecture: ${ctx.productIntelligence!.architectureSummary}`);
    expect(p).toContain('Data model:');
    expect(p).toContain('API surfaces:');
    expect(p).toContain('Risks:');
    expect(p).toContain('Judging approach:');
    expect(p).toContain('Sponsor opportunities:');
  });

  it('deduplicates fields already carried by the STRATEGY block', () => {
    const p = assembly.userPrompt;
    const ids = assembly.sections.map(s => s.id);

    // Sponsor APIs: only the STRATEGY block carries them.
    expect(ids).not.toContain('sponsor_apis');
    expect(p).not.toContain('Sponsor APIs to integrate:');
    expect(p).toContain('Sponsor APIs to prioritize:');

    // Judging criteria: only the per-criterion STRATEGY approach survives.
    expect(ids).not.toContain('judging_criteria');
    expect(p).not.toContain('Detailed Judging Criteria:');
    expect(p).toContain('Judging approach:');

    // Key pages live in the STRATEGY block only (it lists every key screen).
    expect(ids).not.toContain('key_pages');
    expect(p).not.toContain('Key Pages:');
    expect(p).toContain('Key screens:');

    // Feature priority and differentiators stay as full top-level lists — the
    // STRATEGY block only shows a filtered subset (core/sponsor features and
    // the singular PI vision differentiator), so dropping them would lose
    // planning artifacts. Both appear: full list + the block's callout.
    expect(ids).toContain('feature_priority');
    expect(ids).toContain('differentiators');
    expect(p.split('Feature priority:').length - 1).toBe(2);
    expect(p).toContain('Differentiators: test differentiator');
    expect(p).toContain('Differentiator: ');

    // The old "Hackathon Theme" line was a verbatim copy of the problem.
    expect(p).not.toContain('Hackathon Theme:');
  });

  it('never mislabels sponsor integrations or features as Judging Criteria', () => {
    const p = assembly.userPrompt;
    expect(p).not.toContain('Judging Criteria: OpenAI integration');
    expect(p).not.toContain(' integration, ');
  });

  it('reports removed sections with reasons in the diagnostics', () => {
    const reasons = assembly.removed.map(r => `${r.id}:${r.reason}`);
    // Theme is absent from DevpostData — the diagnostics must say so honestly.
    expect(reasons).toContain('theme:no distinct theme available');
    expect(reasons).toContain('sponsor_apis:already carried by STRATEGY block');
    expect(reasons).toContain('judging_criteria:already carried by STRATEGY block');
    expect(reasons).toContain('key_pages:already carried by STRATEGY block');
    // Exactly one reason per section — no duplicate diagnostics entries.
    const ids = assembly.removed.map(r => r.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('reports included sections, token estimates and generation context', () => {
    expect(assembly.sections.length).toBeGreaterThan(0);
    expect(assembly.userTokens).toBeGreaterThan(0);
    expect(assembly.systemTokens).toBeGreaterThan(0);
    expect(assembly.totalTokens).toBe(assembly.userTokens + assembly.systemTokens);
    expect(assembly.withinBudget).toBe(true);
    expect(assembly.includedArtifacts).toContain('product-intelligence');
    // The report is a stable, debuggable string.
    const report = formatGenerationPromptDiagnostics(assembly);
    expect(report).toContain('Included sections');
    expect(report).toContain('Removed sections');
    expect(report).toContain('Generation context');
  });
});

describe('assembleGenerationPrompt — fallback path (no strategy block)', () => {
  it('keeps every field reachable when the STRATEGY block is absent', () => {
    const a = assembleGenerationPrompt(baseInput({
      judgingCriteria: [{ name: 'Innovation', weight: 40 }, { name: 'Impact', weight: 60 }],
      sponsorApis: ['OpenAI'],
      featurePriority: ['core-feed', 'sponsor-ai-tagging'],
      keyPages: ['/', '/demo'],
      differentiators: ['Real-time inference'],
      optimizationBudget: 'balanced',
      rawConstraints: ['must work offline'],
      requiredTechs: ['openai'],
      specificTask: 'Build the dashboard',
    }));

    const p = a.userPrompt;
    expect(p).toContain('Project: hack-project');
    expect(p).toContain('Problem: Reduce food waste in supply chains');
    expect(p).toContain('Judging Criteria: Innovation (40%), Impact (60%)');
    expect(p).toContain('Sponsor APIs to integrate: OpenAI');
    expect(p).toContain('Feature priority: core-feed; sponsor-ai-tagging');
    expect(p).toContain('Key Pages: /, /demo');
    expect(p).toContain('Differentiators: Real-time inference');
    expect(p).toContain('Constraints: Optimization budget: balanced, must work offline');
    expect(p).toContain('Tech Stack: Frontend: Next.js, Backend: Node.js, Database: SQLite, Deployment: Vercel');
    expect(p).toContain('REQUIRED TECHNOLOGIES');
    expect(p).toContain('Task: Generate the landing page');
    expect(p).toContain('Focus on: Build the dashboard');
    expect(p).toContain('This is a HACKATHON project.');
    // Differentiators stay out of Constraints, theme duplication stays out.
    const constraintsLine = a.sections.find(s => s.id === 'constraints')!.content;
    expect(constraintsLine).not.toContain('Differentiator');
    expect(p).not.toContain('Hackathon Theme:');
  });

  it('renders a distinct theme when the parser found one', () => {
    const a = assembleGenerationPrompt(baseInput({ theme: 'AI for Good' }));
    expect(a.userPrompt).toContain('Hackathon Theme: AI for Good');
  });

  it('drops the theme section when it equals the problem statement', () => {
    const a = assembleGenerationPrompt(baseInput({ theme: 'Reduce food waste in supply chains' }));
    expect(a.userPrompt).not.toContain('Hackathon Theme:');
    expect(a.removed.some(r => r.id === 'theme' && r.reason === 'duplicates problem statement')).toBe(true);
  });
});

describe('assembleGenerationPrompt — determinism and snapshot', () => {
  it('is deterministic: identical input → identical prompt and diagnostics', () => {
    const input = baseInput({ judgingCriteria: [{ name: 'Innovation', weight: 40 }] });
    const a = assembleGenerationPrompt(input);
    const b = assembleGenerationPrompt(input);
    expect(a).toEqual(b);
  });

  it('snapshot: locks the exact prompt format for a representative input', () => {
    const a = assembleGenerationPrompt(baseInput({
      submissionRequirements: ['Public demo'],
      judgingCriteria: [{ name: 'Innovation', weight: 40 }],
    }));
    expect(a.userPrompt).toBe([
      'Project: hack-project',
      'Problem: Reduce food waste in supply chains',
      'Submission Requirements: Public demo',
      'Judging Criteria: Innovation (40%)',
      'Tech Stack: Frontend: Next.js, Backend: Node.js, Database: SQLite, Deployment: Vercel',
      'For package.json use these exact versions: next@^14.2.0, react@^18.3.1',
      'Task: Generate the landing page',
      'Focus on: Hero section',
      'This is a HACKATHON project. Make it stand out — judges will compare it against other projects. Solve the specific challenge, integrate sponsor APIs visibly, and make the demo work end-to-end.',
    ].join('\n'));
  });

  it('estimates tokens (~4 chars per token) and stays within budget', () => {
    expect(estimateTokens('abcd')).toBe(1);
    expect(estimateTokens('')).toBe(0);
    const a = assembleGenerationPrompt(baseInput());
    expect(a.userTokens).toBe(estimateTokens(a.userPrompt));
    expect(a.systemTokens).toBe(estimateTokens(a.systemPrompt));
    expect(a.totalTokens).toBeLessThanOrEqual(a.budget);
  });
});

describe('assembleGenerationPrompt — scaffold include list and task focus', () => {
  it('includes the scaffold file list only for the scaffold file type', () => {
    const a = assembleGenerationPrompt(baseInput({
      fileType: 'scaffold',
      specificTask: undefined,
      scaffoldIncludeList: 'Include: package.json, tsconfig.json, src/app/page.tsx, README.md',
    }));
    expect(a.userPrompt).toContain('Include: package.json, tsconfig.json, src/app/page.tsx, README.md');
    expect(a.userPrompt).not.toContain('Focus on:');
  });

  it('emits Focus on only for frontend/backend/database tasks with a specific task', () => {
    const a = assembleGenerationPrompt(baseInput({ fileType: 'config' as const, specificTask: 'x' }));
    expect(a.userPrompt).not.toContain('Focus on:');
  });
});
