import { describe, it, expect } from 'vitest';

import type { InterviewResult } from '../../cli/interview/types.js';
import { buildCodeGenContext, renderStrategyPromptBlock } from '../../cli/pipeline/strategy-adapter.js';
import { WinningStrategyGenerator } from '../../cli/pipeline/strategy.js';
import type { CompetitionAnalysis } from '../../cli/pipeline/types.js';
import { runProductIntelligence } from '../../cli/product-intelligence/orchestrator.js';

function mockAnalysis(): CompetitionAnalysis {
  return {
    analysisId: 'ca-pi-prompt',
    challenge: {
      title: 'AI for Good Hackathon',
      problemStatement: 'Build AI solutions for social impact',
      theme: 'AI for Good',
      difficulty: 'intermediate',
      estimatedParticipants: 200,
      organizer: 'TestOrg',
    },
    judgingCriteria: [
      { name: 'Innovation', weight: 40, weightRaw: '40%', description: 'Originality', priority: 'critical' },
      { name: 'Technical Depth', weight: 30, weightRaw: '30%', description: 'Sophistication', priority: 'high' },
      { name: 'Social Impact', weight: 30, weightRaw: '30%', description: 'Impact', priority: 'high' },
    ],
    sponsorAPIs: [
      { name: 'OpenAI', provider: 'OpenAI', description: 'GPT models', strategicValue: 'must_use' },
    ],
    deliverables: [],
    restrictions: [],
    deadlines: [],
  };
}

/** Run the real runtime path: PI pass → strategy → codegen context. */
function buildContext() {
  const analysis = mockAnalysis();
  const pi = runProductIntelligence(analysis, null);
  const interviewResult: InterviewResult = {
    selectedPrize: null,
    selectedSponsorApis: [],
    optimizationBudget: 'balanced',
    userProjectIdea: null,
    autoGeneratedIdea: pi.winner.oneLiner,
    ideation: pi.brainstorm,
    productIntelligence: pi,
    technologyPreferences: [],
    allAnswers: {},
  };
  const strategy = new WinningStrategyGenerator().generate(analysis, interviewResult);
  return { analysis, pi, strategy, ctx: buildCodeGenContext(analysis, strategy) };
}

describe('Product Intelligence → CodeGenContext', () => {
  it('carries the winning idea, vision and architecture into the codegen context', () => {
    const { pi, ctx } = buildContext();

    expect(ctx.productIntelligence).toBeTruthy();
    const piCtx = ctx.productIntelligence!;
    expect(piCtx.winnerTitle).toBe(pi.winner.title);
    expect(piCtx.visionStatement).toBe(pi.vision.visionStatement);
    expect(piCtx.targetUser).toBe(pi.vision.targetUser);
    expect(piCtx.wowMoment).toBe(pi.vision.wowMoment);
    expect(piCtx.differentiator).toBe(pi.vision.differentiator);
    expect(piCtx.demoStrategy).toBe(pi.vision.demoStrategy);
    expect(piCtx.architectureSummary).toBe(pi.architecture.summary);
    expect(piCtx.mvpScope.length).toBeGreaterThan(0);
    expect(piCtx.dataModel.length).toBeGreaterThan(0);
    expect(piCtx.apiSurfaces.length).toBeGreaterThan(0);
    expect(piCtx.risks.length).toBeGreaterThan(0);
    expect(piCtx.judgingApproach.length).toBeGreaterThan(0);
    expect(piCtx.sponsorOpportunities).toContain('OpenAI');
  });

  it('carries the one-liner and brand name at the top level', () => {
    const { pi, ctx } = buildContext();
    expect(ctx.oneLiner).toBe(pi.vision.oneLiner);
    expect(ctx.brandName).toBe(pi.winner.brandName);
    expect(ctx.sponsorApis).toContain('OpenAI');
  });

  it('produces the same context deterministically', () => {
    const analysis = mockAnalysis();
    const pi = runProductIntelligence(analysis, null);
    const interviewResult: InterviewResult = {
      selectedPrize: null,
      selectedSponsorApis: [],
      optimizationBudget: 'balanced',
      userProjectIdea: null,
      autoGeneratedIdea: pi.winner.oneLiner,
      ideation: pi.brainstorm,
      productIntelligence: pi,
      technologyPreferences: [],
      allAnswers: {},
    };
    const strategy = new WinningStrategyGenerator().generate(analysis, interviewResult);
    const a = buildCodeGenContext(analysis, strategy);
    const b = buildCodeGenContext(analysis, strategy);
    expect(a).toEqual(b);
  });
});

describe('renderStrategyPromptBlock — what the model actually receives', () => {
  it('injects every Product Intelligence field into the STRATEGY prompt block', () => {
    const { pi, ctx } = buildContext();
    const prompt = renderStrategyPromptBlock(ctx);

    // Winning idea + vision
    expect(prompt).toContain(`Winning idea: ${pi.winner.title}`);
    expect(prompt).toContain(`One-liner: ${pi.vision.oneLiner}`);
    expect(prompt).toContain(`Vision: ${pi.vision.visionStatement}`);
    expect(prompt).toContain(`Target users: ${pi.vision.targetUser}`);
    expect(prompt).toContain(`Wow moment: ${pi.vision.wowMoment}`);
    expect(prompt).toContain(`Differentiator: ${pi.vision.differentiator}`);
    expect(prompt).toContain(`Demo strategy: ${pi.vision.demoStrategy}`);
    // Architecture + database + API decisions
    expect(prompt).toContain(`Architecture: ${pi.architecture.summary}`);
    for (const dm of pi.architecture.dataModel) {
      expect(prompt).toContain(dm);
    }
    for (const api of pi.architecture.apiSurfaces) {
      expect(prompt).toContain(api);
    }
    // Risks
    expect(prompt).toContain('Risks:');
    expect(prompt).toContain(pi.vision.risks[0]!.risk);
    expect(prompt).toContain(pi.vision.risks[0]!.mitigation);
    // Judging strategy — per-criterion approach, not just names/weights
    for (const p of pi.judgingPriorities) {
      expect(prompt).toContain(`${p.name} (${p.weight}%)`);
      expect(prompt).toContain(p.approach);
    }
    // Sponsor choices
    expect(prompt).toContain('OpenAI');
    // Feature priorities
    expect(prompt).toContain('Feature priority:');
    // Branding
    expect(prompt).toContain(`Project name: ${pi.winner.brandName}`);
  });

  it('renders empty for a null context (backward-compatible)', () => {
    expect(renderStrategyPromptBlock(null)).toBe('');
  });

  it('falls back to slug name and empty PI section when no PI pass ran', () => {
    const analysis = mockAnalysis();
    const strategy = new WinningStrategyGenerator().generate(analysis);
    const ctx = buildCodeGenContext(analysis, strategy);

    expect(ctx.productIntelligence).toBeUndefined();
    const prompt = renderStrategyPromptBlock(ctx);
    expect(prompt).toContain('STRATEGY:');
    expect(prompt).toContain(`Project name: ${strategy.brandName}`);
    expect(prompt).toContain(`One-liner: ${strategy.oneLiner}`);
  });
});
