import { describe, it, expect } from 'vitest';

import { brainstormIdeas } from '../../cli/ideation/idea-engine.js';
import { GENERIC_NAME_TOKENS } from '../../cli/ideation/types.js';
import type { InterviewResult } from '../../cli/interview/types.js';
import { WinningStrategyGenerator } from '../../cli/pipeline/strategy.js';
import type { CompetitionAnalysis } from '../../cli/pipeline/types.js';
import { runProductIntelligence } from '../../cli/product-intelligence/orchestrator.js';

function mockAnalysis(): CompetitionAnalysis {
  return {
    analysisId: 'ca-strategy',
    challenge: {
      title: 'AI for Good Hackathon',
      problemStatement: 'Build AI solutions for social impact',
      theme: 'AI for Good',
      difficulty: 'intermediate',
      estimatedParticipants: 200,
      organizer: 'TestOrg',
    },
    judgingCriteria: [
      { name: 'Innovation', weight: 40, weightRaw: '40%', description: 'Originality', priority: 'critical' },
      { name: 'Technical Depth', weight: 30, weightRaw: '30%', description: 'Sophistication', priority: 'high' },
      { name: 'Social Impact', weight: 30, weightRaw: '30%', description: 'Impact', priority: 'high' },
    ],
    sponsorAPIs: [
      { name: 'OpenAI', provider: 'OpenAI', description: 'GPT models', strategicValue: 'must_use' },
    ],
    deliverables: [],
    restrictions: [],
    deadlines: [],
  };
}

describe('WinningStrategyGenerator branding', () => {
  it('carries the ideation winner through to the strategy', () => {
    const analysis = mockAnalysis();
    const ideation = brainstormIdeas(analysis, null);
    const interviewResult: InterviewResult = {
      selectedPrize: null,
      selectedSponsorApis: [],
      optimizationBudget: 'balanced',
      userProjectIdea: null,
      autoGeneratedIdea: ideation.winner.oneLiner,
      ideation,
      technologyPreferences: [],
      allAnswers: {},
    };

    const strategy = new WinningStrategyGenerator().generate(analysis, interviewResult);

    expect(strategy.ideation?.winner.id).toBe(ideation.winner.id);
    expect(strategy.brandName).toBe(ideation.winner.brandName);
    expect(strategy.brandName?.length).toBeGreaterThan(0);
    expect(strategy.oneLiner).toBe(ideation.winner.oneLiner);
  });

  it('derives a startup-quality brand name even without an interview', () => {
    const strategy = new WinningStrategyGenerator().generate(mockAnalysis());
    expect(strategy.brandName).toBeTruthy();
    const lower = strategy.brandName!.toLowerCase();
    expect(GENERIC_NAME_TOKENS.includes(lower as (typeof GENERIC_NAME_TOKENS)[number])).toBe(false);
    expect(lower).not.toMatch(/^(smart|my|ai|chat)/);
    expect(strategy.brandName!.length).toBeGreaterThan(4);
  });

  it('is deterministic', () => {
    const analysis = mockAnalysis();
    const a = new WinningStrategyGenerator().generate(analysis);
    const b = new WinningStrategyGenerator().generate(analysis);
    expect(a.brandName).toBe(b.brandName);
    expect(a.ideation).toBeNull();
  });

  it('carries the full product intelligence pass into the strategy', () => {
    const analysis = mockAnalysis();
    const pi = runProductIntelligence(analysis, null);
    const interviewResult: InterviewResult = {
      selectedPrize: null,
      selectedSponsorApis: [],
      optimizationBudget: 'balanced',
      userProjectIdea: null,
      autoGeneratedIdea: pi.winner.oneLiner,
      ideation: pi.brainstorm,
      productIntelligence: pi,
      technologyPreferences: [],
      allAnswers: {},
    };

    const strategy = new WinningStrategyGenerator().generate(analysis, interviewResult);

    expect(strategy.productIntelligence?.winner.id).toBe(pi.winner.id);
    expect(strategy.brandName).toBe(pi.winner.brandName);
    expect(strategy.oneLiner).toBe(pi.vision.oneLiner);
    expect(strategy.architecture).toContain('single-repo');
    // The judge-simulated panel score replaces the heuristic estimate.
    expect(strategy.estimatedJudgeScore).toBe(pi.winner.judgeSimulation.total);
    expect(strategy.differentiators[0]).toBe(pi.vision.differentiator);
  });
});
